const fs = require('fs');

const en = {
  navbar: { home: 'Home', about: 'About', menu: 'Menu', gallery: 'Gallery', location: 'Location', orderOnline: 'Order Online' },
  hero: { title: 'Milan Nepal Westend Saptarangi', tagline: 'Aromatic, deeply flavored Himalayan cuisine — fresh ingredients, heady spices, vibrant colors', orderOnWolt: 'Order on Wolt', scroll: 'Scroll' },
  about: { ourStory: 'Our Story', title1: 'A Taste of the ', title2: 'Himalayas', p1_1: 'Nestled in the heart of Westend, Espoo, ', p1_strong: 'Milan Nepal – Saptarangi', p1_2: ' brings the authentic flavors of Nepal and the greater Himalayan region to Finland. Our name, ', p1_em: 'Saptarangi', p1_3: ', means "seven colors" — a celebration of the vibrant, multi-hued tapestry of Himalayan cuisine.', p2: 'Every dish begins with the freshest ingredients — hand-ground spice blends, aromatic herbs, and time-honored recipes passed down through generations. From our tandoor-grilled meats to our slow-simmered curries, each plate is a journey through the aromatic kitchens of Kathmandu, Pokhara, and beyond.', p3: 'We believe in family hospitality. When you dine with us, you\'re not just a guest — you\'re family. Our warm, welcoming atmosphere and attentive service are as much a part of the experience as the food itself.', yearsOfTradition: 'Years of Tradition', authenticDishes: 'Authentic Dishes', freshIngredients: 'Fresh Ingredients' },
  menu: { title: 'Our Menu', subtitle: 'Discover', description: 'From aromatic starters to hearty mains, each dish is crafted with authentic Himalayan spices and the freshest ingredients.', loading: 'Loading menu…' },
  gallery: { subtitle: 'Gallery', title: 'A Visual Feast' },
  order: { orderOnline: 'Order Online', enjoyAtHome: 'Enjoy at Home', description: 'Can\'t make it to the restaurant? Order your favorite Himalayan dishes for delivery through Wolt, or call us for takeaway.', orderOnWolt: 'Order on Wolt', callForTakeaway: 'Call for Takeaway', info: 'Delivery available through Wolt · Takeaway by phone: +358 44 777 3636' },
  location: { title: 'Find Us', subtitle: 'Visit Our Restaurant', addressTitle: 'Address', addressVal: 'Westendintie 99 D\\n02160 Espoo, Finland', parking: 'Near Tapiola', freeParking: '🅿️ Free Parking', hoursTitle: 'Opening Hours', lunchServed: 'Lunch served weekdays 10:30 – 15:00', callUs: 'Call Us', getDirections: 'Get Directions' },
  footer: { description: 'Authentic Himalayan cuisine crafted with love, fresh ingredients, and generations of tradition.', quickLinks: 'Quick Links', contact: 'Contact', parkingInfo: 'Near Tapiola · Free parking', hours: 'Hours', monThu: 'Mon–Thu', friday: 'Friday', saturday: 'Saturday', sunday: 'Sunday', followUs: 'Follow Us', allRightsReserved: 'All rights reserved.', comingSoon: 'Coming soon' },
  nav: { about: 'Our Story', menu: 'Menu', gallery: 'Gallery', reserve: 'Reservations', location: 'Location' }
};

const fi = {
  navbar: { home: 'Etusivu', about: 'Tietoa meistä', menu: 'Ruokalista', gallery: 'Galleria', location: 'Sijainti', orderOnline: 'Tilaa netistä' },
  hero: { title: 'Milan Nepal Westend Saptarangi', tagline: 'Aromaattinen ja syvästi maustettu Himalajan keittiö — tuoreet ainesosat, huumaavat mausteet, eloisat värit', orderOnWolt: 'Tilaa Woltista', scroll: 'Vieritä' },
  about: { ourStory: 'Tarinamme', title1: 'Makuja ', title2: 'Himalajalta', p1_1: 'Espoon Westendin sydämessä sijaitseva ', p1_strong: 'Milan Nepal – Saptarangi', p1_2: ' tuo Nepalin ja laajemman Himalajan alueen autotenttiset maut Suomeen. Nimemme, ', p1_em: 'Saptarangi', p1_3: ', tarkoittaa "seitsemää väriä" — juhlistaen Himalajan keittiön eloisaa ja monisävyistä kirjoa.', p2: 'Jokainen annos alkaa tuoreimmista ainesosista — käsin jauhetuista mausteseoksista, aromaattisista yrteistä ja sukupolvelta toiselle siirtyneistä perinteisistä resepteistä. Tandoor-grillatuista lihoista hitaasti haudutettuihin curryihin, jokainen lautanen on matka Kathmandun, Pokharan ja laajempien alueiden aromaattisiin keittiöihin.', p3: 'Uskomme perhevieraanvaraisuuteen. Kun ruokailet kanssamme, et ole vain vieras — olet perhettä. Lämmin, kutsuva ilmapiirimme ja huomaavainen palvelumme ovat yhtä suuri osa elämystä kuin itse ruokakin.', yearsOfTradition: 'Vuotta perinnettä', authenticDishes: 'Autenttista annosta', freshIngredients: 'Tuoreita aineksia' },
  menu: { title: 'Ruokalistamme', subtitle: 'Tutustu', description: 'Aromaattisista alkuruoista runsaisiin pääruokiin, jokainen annos on valmistettu aidoilla Himalajan mausteilla ja tuoreimmista aineksista.', loading: 'Ladataan ruokalistaa…' },
  gallery: { subtitle: 'Galleria', title: 'Visuaalinen nautinto' },
  order: { orderOnline: 'Tilaa netistä', enjoyAtHome: 'Nauti kotona', description: 'Etkö pääse ravintolaan? Tilaa suosikki Himalaja-annoksesi kotiinkuljetuksella Woltin kautta tai soita meille noutotilausta varten.', orderOnWolt: 'Tilaa Woltista', callForTakeaway: 'Soita ja tilaa nouto', info: 'Kotiinkuljetus Woltin kautta · Noutotilaukset puhelimitse: +358 44 777 3636' },
  location: { title: 'Löydä meidät', subtitle: 'Vieraile ravintolassamme', addressTitle: 'Osoite', addressVal: 'Westendintie 99 D\\n02160 Espoo, Finland', parking: 'Lähellä Tapiolaa', freeParking: '🅿️ Ilmainen pysäköinti', hoursTitle: 'Aukioloajat', lunchServed: 'Lounas arkisin 10:30 – 15:00', callUs: 'Soita meille', getDirections: 'Hae reittiohjeet' },
  footer: { description: 'Aitoa Himalajan keittiötä rakkaudella, tuoreilla aineksilla ja sukupolvien perinteellä.', quickLinks: 'Pikalinkit', contact: 'Yhteystiedot', parkingInfo: 'Lähellä Tapiolaa · Ilmainen pysäköinti', hours: 'Aukioloajat', monThu: 'Ma–To', friday: 'Perjantai', saturday: 'Lauantai', sunday: 'Sunnuntai', followUs: 'Seuraa meitä', allRightsReserved: 'Kaikki oikeudet pidätetään.', comingSoon: 'Tulossa pian' },
  nav: { about: 'Tarinamme', menu: 'Ruokalista', gallery: 'Galleria', reserve: 'Varaukset', location: 'Sijainti' }
};

const sv = {
  navbar: { home: 'Hem', about: 'Om oss', menu: 'Meny', gallery: 'Galleri', location: 'Hitta hit', orderOnline: 'Beställ online' },
  hero: { title: 'Milan Nepal Westend Saptarangi', tagline: 'Aromatisk och smakrik mat från Himalaya — färska ingredienser, berusande kryddor, livfulla färger', orderOnWolt: 'Beställ på Wolt', scroll: 'Skrolla' },
  about: { ourStory: 'Vår historia', title1: 'Smaker från ', title2: 'Himalaya', p1_1: 'Beläget i hjärtat av Westend, Esbo, tar ', p1_strong: 'Milan Nepal – Saptarangi', p1_2: ' de autentiska smakerna från Nepal och Himalaya till Finland. Vårt namn, ', p1_em: 'Saptarangi', p1_3: ', betyder "sju färger" — en hyllning till det livfulla och färgstarka köket från Himalaya.', p2: 'Varje rätt börjar med de färskaste ingredienserna — handmalda kryddblandningar, aromatiska örter och traditionella recept som gått i arv i generationer. Från vårt tandoori-grillade kött till våra långkokta curryrätter, varje tallrik är en resa genom de aromatiska köken i Kathmandu, Pokhara och bortom.', p3: 'Vi tror på familjegästfrihet. När du äter hos oss är du inte bara en gäst — du är familj. Vår varma, välkomnande atmosfär och uppmärksamma service är lika mycket en del av upplevelsen som själva maten.', yearsOfTradition: 'År av tradition', authenticDishes: 'Autentiska rätter', freshIngredients: 'Färska råvaror' },
  menu: { title: 'Vår meny', subtitle: 'Upptäck', description: 'Från aromatiska förrätter till rejäla huvudrätter, varje rätt är tillagad med autentiska kryddor från Himalaya och de färskaste ingredienserna.', loading: 'Laddar meny…' },
  gallery: { subtitle: 'Galleri', title: 'En visuell fest' },
  order: { orderOnline: 'Beställ online', enjoyAtHome: 'Njut hemma', description: 'Har du inte tid att besöka restaurangen? Beställ dina favoriträtter från Himalaya för hemleverans via Wolt, eller ring oss för avhämtning.', orderOnWolt: 'Beställ på Wolt', callForTakeaway: 'Ring för avhämtning', info: 'Hemleverans via Wolt · Avhämtning via telefon: +358 44 777 3636' },
  location: { title: 'Hitta oss', subtitle: 'Besök vår restaurang', addressTitle: 'Adress', addressVal: 'Westendintie 99 D\\n02160 Esbo, Finland', parking: 'Nära Hagalund', freeParking: '🅿️ Gratis parkering', hoursTitle: 'Öppettider', lunchServed: 'Lunch serveras vardagar 10:30 – 15:00', callUs: 'Ring oss', getDirections: 'Få vägbeskrivning' },
  footer: { description: 'Autentiskt Himalaya-kök skapat med kärlek, färska råvaror och generationers tradition.', quickLinks: 'Snabblänkar', contact: 'Kontakt', parkingInfo: 'Nära Hagalund · Gratis parkering', hours: 'Öppettider', monThu: 'Mån–Tor', friday: 'Fredag', saturday: 'Lördag', sunday: 'Söndag', followUs: 'Följ oss', allRightsReserved: 'Alla rättigheter förbehållna.', comingSoon: 'Kommer snart' },
  nav: { about: 'Vår historia', menu: 'Meny', gallery: 'Galleri', reserve: 'Bokningar', location: 'Plats' }
};

if (!fs.existsSync('dictionaries')) fs.mkdirSync('dictionaries');
fs.writeFileSync('dictionaries/en.json', JSON.stringify(en, null, 2));
fs.writeFileSync('dictionaries/fi.json', JSON.stringify(fi, null, 2));
fs.writeFileSync('dictionaries/sv.json', JSON.stringify(sv, null, 2));
console.log("Dictionaries updated successfully!");
